<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Entrypoints
    |--------------------------------------------------------------------------
    |
    | The files listed below will be considered entry points and will be
    | included in the build manifest regardless of whether they are
    | explicitly imported in your JavaScript entrypoint.
    |
    */

    'entrypoints' => [
        'resources/js/app.js',
        'resources/css/app.css',
    ],

    /*
    |--------------------------------------------------------------------------
    | Build Path
    |--------------------------------------------------------------------------
    |
    | This is the directory where the build assets generated by Vite
    | should be stored. It should match the "build.outDir" value in your
    | vite.config.js.
    |
    */

    'build_path' => 'build',

    /*
    |--------------------------------------------------------------------------
    | Hot Module Replacement (HMR) Configuration
    |--------------------------------------------------------------------------
    |
    | If you are using the Vite development server for local development,
    | you may specify its host and port below.
    |
    */

    'hmr' => [
        'host' => 'localhost',
    ],

];
